spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://localhost:3306/blog?verifyServerCertificate=false&useSSL=false&characterEncoding=utf-8
    username: root
    password: zwdsxwd..
    
  application:
    name: blog-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
  http:
    converters:
      preferred-json-mapper: jackson


eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8999/eureka
  instance:
    hostname: localhost


info:
  profile: default
  from: git-repo